### ISSUE TITLE
New Release - Python 3.7 Support?

### ISSUE THREAD

**Issue by leonsmith** [pyeve/cerberus#478]
Used Cerberus version / latest commit: 1.2 

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve. _(I don't actaully know what this question is asking but that might just be my poor english skills)_

----

#### Use-case abstract

I have another library using this amazing package but would like to support 3.7 whilst cerberus lastest release only supports up to python 3.6.

----

#### Bug report / Feature request

Looks like the last release was back in April last year and considering this has a passing test suite with 3.7 it would be super cool to get a point release out with 3.7 support.

Anything I can do to help get this rolling?

**Comment by eirnym** [comment]
PR to show the support and run tests will be very useful.

For 3.8, the situation is a bit different, as this library uses ABC classes imported from `collections`, not from `collections.abc`. This  behaviour is discouraged since `Python 3` is out and these collections are absent in `3.8` in `collections` module. The `collections.abc` module is absent in Python 2, so  the support could be done with the following `try-import-except` without breaking compatibility.

```python
try:
    from collections.abc import Hashable, Iterable, Mapping, Sequence
except ImportError:
    from collections import Hashable, Iterable, Mapping, Sequence
```

Currently, only a few files have such incompatibilities which is very easy to fix.
* [cerberus/validator.py](https://github.com/pyeve/cerberus/blob/master/cerberus/validator.py)
* [cerberus/errors.py](https://github.com/pyeve/cerberus/blob/master/cerberus/errors.py)
* [cerberus/schema.py](https://github.com/pyeve/cerberus/blob/master/cerberus/schema.py)

**Comment by funkyfuture** [comment]
@eirnym that deprecation is already addressed in the `platform` module.

the tests are not run against Python 3.8 yet. wasn't there talk that these deprecations (or the actual removal) of the classes in question would be revoked with 3.8? but i can't find anything in this regard in the current pre-release changelog.

**Comment by eirnym** [comment]
The Python 3.7.3 shows already these warnings as documented in [whatsnew for Python 3.7](https://docs.python.org/3/whatsnew/3.7.html#id3) and in referenced [BPO](https://bugs.python.org/issue25988)

**Comment by funkyfuture** [comment]
version 1.3 that supports Python3.7 is released. mind though, that [there are bugs](https://github.com/pyeve/cerberus/milestone/8?closed=1) in it, we hope to provide a gub fix release soonish.
