### ISSUE TITLE
Add configurable order of normalization and validation

### ISSUE THREAD

**Issue by erictwalker18** [pyeve/cerberus#555]
Used Cerberus version / latest commit: …

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

- [x] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

I have a schema and document like:

```python
schema = {'foo': {'type': 'string', 'rename': 'bar'}, 'qux': {'type': 'string', 'readonly': True}}
document = {'foo': 'baz', 'qux':'quux', 'unknown':'value'}
```

I'd like to validate this document, but I'd have to edit the schema to `{'foo': {'rename': 'bar'}, 'bar':{'type': 'string'}, 'qux': {'type': 'string', 'readonly': True}}` in order to get a passing validation, which I'm not excited about.

----

#### Bug report / Feature request

I'd like the be able to specify the order of the various normalization steps and validation, along the lines of:

```python
schema = {'foo': {'type': 'string', 'rename': 'bar'}, 'qux': {'type': 'string', 'readonly': True}}
document = {'foo': 'baz', 'qux':'quux', 'unknown':'value'}
want = {'bar': 'baz'}
order = ['purge_readonly', 'validate', 'purge_unknown', 'rename']
validator = Validator(schema)
assert want == validator.validated(document, order=order)
```

**Comment by funkyfuture** [comment]
ordering rule evaluation might be something that may be possible to a degree on the class level with the next major version that i already did some work on. mixing normalization and validation will certainly not be doable.

in order to get hold of your excitement, i recommend that you either adjust your expectations (the schema that works is just correct) or address order by splitting the rules into a series of schema that a document is evaluated against in order.
