### ISSUE TITLE
Crash with __debug__ != True

### ISSUE THREAD

**Issue by jonyscathe** [pyeve/cerberus#567]
Used Cerberus version / latest commit: 1.3.3

- [ ] I have the capacity to improve the docs when my problem is solved.
- [ ] I have the capacity to submit a patch when a bug is identified.

- [ ] My question does not concern a practical use-case that I can't figure out
      to solve.

----

#### Use-case abstract

As far as I can tell, there was a breaking change from 1.3.2 to 1.3.3

----

#### Bug report / Feature request

I am using the example code from the how to use page:
    from cerberus import Validator

    schema = {'name': {'type': 'string'}}
    v = Validator(schema)
    document = {'name': 'john doe'}
    print(v.validate(document))

If I have this code in a file 'test.py' then run python test.py it all works fine and 'True' is printed.
If I run python -O test.py, removing __debug__ dependent statements then I get the following:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    v = Validator(schema)
  File "/usr/local/lib/python3.8/site-packages/cerberus/validator.py", line 193, in __init__
    self.schema = kwargs.get('schema', None)
  File "/usr/local/lib/python3.8/site-packages/cerberus/validator.py", line 604, in schema
    self._schema = DefinitionSchema(self, schema)
  File "/usr/local/lib/python3.8/site-packages/cerberus/schema.py", line 72, in __init__
    self.validation_schema = SchemaValidationSchema(validator)
  File "/usr/local/lib/python3.8/site-packages/cerberus/schema.py", line 307, in __init__
    'schema': validator.rules,
AttributeError: 'BareValidator' object has no attribute 'rules'

This seems to be down to two things. BareValidator does not have an attribute rules, only the InspectedValidator.
And when __debug__ is None, then as of 1.3.3 a Validator defaults to a BareValidator rather than an InspectedValidator (lines 1682 onwards of validator.py) whereas 1.3.2 always used an InspectedValidator. Only found this out when deploying a new container to a server - I hadn't realised that when using pytest __debug__ is True...

**Comment by funkyfuture** [comment]
thanks for reporting! indeed i was under the assumption that the `BareValidator` is alike the `UnconcernedValidator` in the current development branch. hence i'm currently looking to introduce something similar to the `1.3` branch. i'm not too happy with that because the result will be more complicated and this 'naturally grown' architecture has been re-implemented for the next major version to overcome unnecessary complexity.

i can't anticipate when i'll have finished a patch, but would immediately release a bug fix release then. as you have already done research with regards to `pytest`, can you propose a test case?

or, we come to the conclusion that Cerberus 1.3 cannot be used without the debug flag set!? cc @sujanadiga

**Comment by jonyscathe** [comment]
I'm not entirely sure how to test this case in pytest.
I found that I could run all of my tests without debug by running 'python -O -m pytest', but not sure how to do some tests with and some tests without.

**Comment by funkyfuture** [comment]
i just released Cerberus 1.3.4 that i hope will solve your issues. see https://github.com/pyeve/cerberus/issues/557#issuecomment-832953546 too.
